version: '3'

services:
  url_shorten:
    image: web_image:latest
    volumes:
      - .:/home/web_service
    ports:
      - "5000:5000"
    environment:
      - SERVICE_TYPE=shorten
    depends_on:
      - url_auth
    command: python3 ./url_service/app_url.py

  url_auth:
    image: web_image:latest
    volumes:
      - .:/home/web_service
    ports:
      - "5001:5001"
    environment:
      - SERVICE_TYPE=auth
    command: python3 ./auth_service/app_auth.py
