version: '3'

services:
  url_shorten:
    image: web_image:latest
    volumes:
      - ./db:/home/web_service/db
    ports:
      - "5000:5000"
    depends_on:
      - url_auth
    command: python3 ./url_service/app_url.py

  url_auth:
    image: web_image:latest
    volumes:
      - ./db:/home/web_service/db
    ports:
      - "5001:5001"
    command: python3 ./auth_service/app_auth.py
