version: '3'

services:
  url_shorten:
    image: wujianchun123/url_service:latest
    volumes:
      - ../db:/home/url_service/db
    ports:
      - "5000:5000"
    depends_on:
      - url_auth
    command: python3 ./app_url.py

  url_auth:
    image: wujianchun123/auth_service:latest
    volumes:
      - ../db:/home/auth_service/db
    ports:
      - "5001:5001"
    command: python3 ./app_auth.py
