apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:

      containers:
      - name: url-shorten
        image: wujianchun123/url_service:latest
        command: ["python3", "./app_url.py"]
        ports:
        - containerPort: 5000
        volumeMounts:
        - name: data
          mountPath: /home/url_service/db
      - name: url-auth
        image: wujianchun123/auth_service:latest
        command: ["python3", "./app_auth.py"]
        ports:
        - containerPort: 5001
        volumeMounts:
        - name: data
          mountPath: /home/auth_service/db
      volumes:
      - name: data
        nfs:
          #server: "nfs-service.default.svc.cluster.local"
          server: 192.168.196.227
          path: "/web"
