apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  nginx.conf: |
    events {}
    http {
        server {
            listen 80;

            location /url-shorten/ {
                proxy_pass http://url-shorten-svc:5000/;
            }

            location /url-auth/ {
                proxy_pass http://url-auth-svc:5001/;
            }
        }
    }

