apiVersion: v1
kind: Service
metadata:
  name: url-auth-svc
spec:
  type: NodePort
  selector:
    app: my-app
  ports:
    - protocol: TCP
      port: 5001
      targetPort: 5001
      nodePort: 32001
