apiVersion: v1
kind: Service
metadata:
  name: url-shorten-svc
spec:
  type: NodePort
  selector:
    app: my-app
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: 32000
